INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (1, '광주 서구 금호동', '아파트', '집', true, 2);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (2, '광주 서구 금호동', '아파트', '집', true, 6);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (6, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 2);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (7, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 2);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (9, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 3);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (13, '광주 광산구 고봉로 2', '', '집', true, 10);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (14, '광주 서구 금호동', '아파트', '집', true, 11);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (15, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 3);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (16, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 3);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (17, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', true, 3);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (18, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 3);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (19, '광주 광산구 고봉로 2', '201호', '집', true, 12);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (20, '서울 용산구 한남동', '유엔빌리지', '살고싶다.', true, 13);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (21, '광주 광산구 고봉로 2', '201호', '마이홈', true, 14);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (22, '광주 광산구 고봉로 2', '201호', '우리집', true, 15);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (23, '광주 광산구 하남산단6번로 133', '삼성전자 그린시티 주차장 G5 자전거 보관소', '싸피', true, 16);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (27, '광주 광산구 장덕동 1508', '행복한집 204호', '자취방', true, 17);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (28, '광주 북구 하남대로 788', '1234', '111111', true, 18);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (29, '경기 성남시 분당구 판교대장로 1', '', '', true, 19);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (30, '경기 파주시 가나무로 79', '302호', '302호', true, 20);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (31, '광주 광산구 장덕동 1082', '미래안 205호', '집', true, 21);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (32, '광주 광산구 하남산단6번로 2', '싸피', '싸피', true, 22);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (33, '전북 순창군 쌍치면 피노길 8', '화이팅', '주소', true, 23);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (34, '경기 화성시 남양읍 장덕동길 7-6', '1', '1', true, 24);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (35, '광주 광산구 가마길 2-21', '히히', '아무곳', true, 25);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (36, '광주 광산구 장덕동 1577', '하늘채 201호', '자취방', true, 26);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (37, '광주 광산구 가마길 2-21', '', '', false, 27);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (38, '광주 광산구 고봉로 2', '', '', true, 28);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (39, '광주 광산구 고봉로 2', '', '', true, 29);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (40, '광주 광산구 고봉로 2', '', '', true, 30);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (41, '광주 광산구 고봉로 2', '', '', true, 31);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (42, '광주 광산구 고봉로 2', '', '', true, 32);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (43, '광주 광산구 고봉로 2', '', '', true, 33);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (44, '광주 광산구 고봉로 2', '', '', true, 34);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (45, '광주 광산구 고봉로 2', '', '', true, 35);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (46, '서울 동작구 서달로 50-14', '', '', true, 36);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (47, '사우디아라바아 알 나스르', '라커룸 7번방', '씨우', true, 37);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (49, '광주 광산구 고봉로 2', 'ㅁㄴㅇㄹ', 'ㅁㄴㅇㄹ', true, 27);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (51, '사우디아라바아 알 나스르', '라커룸 7번방', '씨우', true, 38);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (54, '광주 서구 계수로 51', '어디지여긴', '본가', false, 26);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (55, '광주 광산구 고봉로 2', 'ㅁㅇㄴㄹ', 'ㅁㄴㅇ', true, 1);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (56, '광주광역시 서구 금호동', '아파트', '집', true, 39);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (58, '광주광역시 서구 금호동', '아파트', '집', true, 40);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (59, '광주 광산구 하남산단6번로 133', '삼성전자 그린시티 주차장 G5 자전거 보관소', '싸피', false, 41);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (60, '광주 광산구 하남산단6번로 107', '삼성전자 광주그린시티2캠퍼스', '싸피', true, 41);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (61, '광주 광산구 하남산단6번로 107', '삼성전자 그린시티 주차장 G5 자전거 보관소', '싸피', true, 42);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (62, '광주 광산구 하남산단6번로 107', '삼성전자 그린시티 주차장 G5 자전거 보관소', '싸피', true, 43);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (63, '광주 광산구 하남산단6번로 107', '삼성전자 그린시티 주차장 G5 자전거 보관소', '싸피', false, 44);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (64, '광주 광산구 하남산단6번로 107', '삼성전자 그린시티 주차장 G5 자전거 보관소', '싸피', false, 45);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (65, '광주 광산구 하남산단6번로 107', '삼성전자 그린시티 주차장 G5 자전거 보관소', '싸피', true, 46);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (67, '광주 광산구 하남산단6번로 107', '삼성전자 그린시티 주차장 G5 자전거 보관소', '싸피', true, 48);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (69, '광주 광산구 하남산단6번로 107', '삼성전자 그린시티 주차장 G5 자전거 보관소', '싸피', true, 50);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (70, '광주 광산구 하남산단6번로 107', '삼성전자 그린시티 주차장 G5 자전거 보관소', '싸피', false, 51);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (71, '광주 광산구 흑석동 759-1', '여름201호', '우리집', false, 1);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (72, '광주 광산구 흑석동 759-1', '여름201호', '우리집', false, 1);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (75, '서울 동작구 서달로 50-14', 'ㅁㄴㅇㄹ', 'ㅁㄴㅇㄹ', false, 1);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (76, '서울 동작구 서달로 50-14', '', '', false, 1);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (77, '광주 광산구 흑석동 759-1', '여름 201호', '우리집', true, 52);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (80, '경기 성남시 분당구 판교역로 4', ' hello222', '판교', true, 47);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (83, '경기 성남시 분당구 판교역로 4', '판교', '판교', true, 54);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (84, '광주 광산구 용아로297번길 17', '집', '집이요', true, 51);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (85, '광주 광산구 장덕동 1508', '햄벅한집 202호', '자취방', true, 53);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (86, '전남 고흥군 동강면 고흥로 4532-79', '1', '2', true, 55);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (89, '제주특별자치도 서귀포시 대정읍 대한로 632', '.', '.', true, 56);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (90, '서울 종로구 종로 1', '교보생명빌', '교멘', true, 49);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (91, '광주 광산구 하남산단6번로 107', 'GTC동 2층 SSAFY 교육장1', '교육장', true, 57);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (93, '광주 광산구 하남산단6번로 57', 'kbi 하남 기숙사동', '자취방', false, 57);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (94, '광주광역시 서구 금호동', '아파트', '집', true, 58);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (95, '광주광역시 서구 금호동', '아파트', '집', true, 59);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (96, '광주 광산구 사암로 501', '22', 'ㅇㅇ', true, 60);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (97, '광주 광산구 흑석동 759-1', '여름 201호', '우리집입니당', true, 61);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (98, '광주 광산구 흑석동 759-1', '여름 201호', '자취방', false, 52);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (99, '광주 광산구 흑석동 759-1', '여름 201호 ', '우리집', true, 62);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (100, '광주 광산구 도천남길 41-60', '수완애', '', true, 63);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (101, '서울 송파구 송파나루길 15', '', '', true, 64);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (102, '광주 광산구 하남산단6번로 107', 'GTC센터 2층 수정된 C204팀', 'SSAFY 광주캠퍼스(수정)', false, 65);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (103, '서울 강남구 테헤란로 212', '17층', '멀티캠퍼스 역삼', true, 65);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (104, '광주 광산구 하남산단6번로 133', '삼성전자 그린시티 주차장 G5 자전거 보관소', '싸피', true, 66);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (105, '광주 광산구 흑석동 759-1', '여름 201호', '우리집', true, 67);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (106, '전북 전주시 덕진구 세병로 41', '', '', true, 69);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (107, '전남 순천시 서면 고룡길 19-9', '좋은곳', '집', true, 70);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (108, '광주 광산구 흑석동 759-1', '여름 201호', '우리집', true, 71);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (109, '광주 광산구 흑석동 759-1', '여름201호', '우리집', true, 72);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (110, '광주 광산구 흑석동 759-1', '여름 201호', '우리집', true, 73);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (112, '광주 광산구 하남산단6번로 107', '삼성전자 광주그린시티2캠퍼스', 'SSAFY', true, 74);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (113, '서울 강남구 테헤란로 212', '멀티캠퍼스 17층', '멀캠 역삼', true, 75);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (114, '서울 강남구 테헤란로 212', '멀티캠퍼스 17층', '멀캠 역삼', true, 76);
