INSERT INTO alfs.board (id, comment, content, title, member_id) VALUES (1, null, '테스트 내용', '상품 관련 문의 드립니다.', 2);
INSERT INTO alfs.board (id, comment, content, title, member_id) VALUES (2, '안녕안녕이건내답글이야', '수정할 내용!', '배송 관련 문의 드립니다.', 2);
INSERT INTO alfs.board (id, comment, content, title, member_id) VALUES (3, '우측의 뱃지에 마우스를 올려 확인할 수 있습니다.', '내용', '알러지 정보를 어디서 확인할 수 있나요?', 2);
INSERT INTO alfs.board (id, comment, content, title, member_id) VALUES (4, '답변 드립니다~~.', '나문희 ㅋ', '기피 식품은 알러지와 관련 없는 건가요?', 61);
INSERT INTO alfs.board (id, comment, content, title, member_id) VALUES (5, 'ㅅㄷㄴㅅ', 'ㅁㄴㅇㅎㅁㄶㅁㄴㅇㅎㅁㄴㅇㅎㅁㄴㅇㅎㅁㄶ', '환불은 어떻게 진행되나요?', 61);
INSERT INTO alfs.board (id, comment, content, title, member_id) VALUES (6, '아님 그거', 'ㅎㅇㅎㅁ', '교환하고 싶어요', 61);
INSERT INTO alfs.board (id, comment, content, title, member_id) VALUES (7, '그거 아님', 'safa', '알러지 필터 기능 관련 문의드립니다.', 62);
INSERT INTO alfs.board (id, comment, content, title, member_id) VALUES (8, '!!!!', '!!!!', '문의 드립니다.', 41);
INSERT INTO alfs.board (id, comment, content, title, member_id) VALUES (9, '그럼 먹지마!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!', '불닭볶음면 너무 매워요', '구매 관련 문의 드립니다.', 65);
INSERT INTO alfs.board (id, comment, content, title, member_id) VALUES (10, 'ㅁ닝런ㅁ이;ㅓㅣㅁㄴ앟ㄴ잏ㅇㄴ', 'ㅠㅠ', '상품 관련 문의 드립니다.', 71);
INSERT INTO alfs.board (id, comment, content, title, member_id) VALUES (11, '우측의 뱃지 정보에 마우스를 올려 내용을 확인할 수 있습니다.', '알러지 필터 기능에 대해 문의드립니다.', '알러지 필터 기능에 대해 문의드립니다.', 74);
