INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (1, '광주 서구 금호동', '아파트', '집', false, 2);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (2, '광주 서구 금호동', '아파트', '집', true, 6);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (3, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 1);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (4, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 1);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (5, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 2);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (6, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', true, 2);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (7, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 2);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (8, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 2);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (9, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 3);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (10, '광주 광산구 고봉로 2', 'ㅁㄴㅇㄹ', '집', true, 7);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (11, '광주 광산구 고봉로 2', '', '집', true, 8);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (12, '광주 광산구 고봉로 2', '', '집', true, 9);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (13, '광주 광산구 고봉로 2', '', '집', true, 10);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (14, '광주 서구 금호동', '아파트', '집', true, 11);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (15, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 3);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (16, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 3);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (17, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', true, 3);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (18, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 3);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (19, '광주 광산구 고봉로 2', '201호', '집', true, 12);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (20, '서울 용산구 한남동', '유엔빌리지', '살고싶다.', true, 13);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (21, '광주 광산구 고봉로 2', '201호', '마이홈', true, 14);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (22, '광주 광산구 고봉로 2', '201호', '우리집', true, 15);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (23, '광주 광산구 하남산단6번로 133', '삼성전자 그린시티 주차장 G5 자전거 보관소', '싸피', true, 16);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (25, '광주 광산구 고봉로 2', 'ㅁㄴㅇㄹ', 'ㅁㄴㅇㄹ', true, 1);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (26, '광주 광산구 고봉로 2', '여름 201호', '여름', false, 1);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (27, '광주 광산구 장덕동 1508', '행복한집 204호', '자취방', true, 17);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (28, '광주 북구 하남대로 788', '1234', '111111', true, 18);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (29, '경기 성남시 분당구 판교대장로 1', '', '', true, 19);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (30, '경기 파주시 가나무로 79', '302호', '302호', true, 20);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (31, '광주 광산구 장덕동 1082', '미래안 205호', '집', true, 21);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (32, '광주 광산구 하남산단6번로 2', '싸피', '싸피', true, 22);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (33, '전북 순창군 쌍치면 피노길 8', '화이팅', '주소', true, 23);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (34, '경기 화성시 남양읍 장덕동길 7-6', '1', '1', true, 24);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (35, '광주 광산구 가마길 2-21', '히히', '아무곳', true, 25);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (36, '광주 광산구 장덕동 1577', '하늘채 201호', '자취방', true, 26);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (37, '광주 광산구 가마길 2-21', '', '', false, 27);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (38, '광주 광산구 고봉로 2', '', '', true, 28);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (39, '광주 광산구 고봉로 2', '', '', true, 29);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (40, '광주 광산구 고봉로 2', '', '', true, 30);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (41, '광주 광산구 고봉로 2', '', '', true, 31);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (42, '광주 광산구 고봉로 2', '', '', true, 32);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (43, '광주 광산구 고봉로 2', '', '', true, 33);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (44, '광주 광산구 고봉로 2', '', '', true, 34);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (45, '광주 광산구 고봉로 2', '', '', true, 35);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (46, '서울 동작구 서달로 50-14', '', '', true, 36);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (47, '사우디아라바아 알 나스르', '라커룸 7번방', '씨우', true, 37);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (48, '광주 광산구 고봉로 2', 'ㅁㄴㅇㄹ', 'ㅁㄴㅇㄹ', false, 1);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (49, '광주 광산구 고봉로 2', 'ㅁㄴㅇㄹ', 'ㅁㄴㅇㄹ', true, 27);
