INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (1, '광주 서구 금호동', '아파트', '집', false, 2);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (2, '광주 서구 금호동', '아파트', '집', true, 6);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (3, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 1);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (4, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 1);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (5, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 2);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (6, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', true, 2);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (7, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 2);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (8, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 2);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (9, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 3);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (10, '광주 광산구 고봉로 2', 'ㅁㄴㅇㄹ', '집', true, 7);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (11, '광주 광산구 고봉로 2', '', '집', true, 8);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (12, '광주 광산구 고봉로 2', '', '집', true, 9);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (13, '광주 광산구 고봉로 2', '', '집', true, 10);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (14, '광주 서구 금호동', '아파트', '집', true, 11);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (15, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 3);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (16, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 3);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (17, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 3);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (18, '서울특별시 강남구 역삼동', '그 어딘가', '멀티캠퍼스 역삼', false, 3);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (19, '광주 광산구 고봉로 2', '201호', '집', true, 12);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (20, '서울 용산구 한남동', '유엔빌리지', '살고싶다.', true, 13);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (21, '광주 광산구 고봉로 2', '201호', '마이홈', true, 14);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (22, '광주 광산구 고봉로 2', '201호', '우리집', true, 15);
INSERT INTO alfs.address (id, address_1, address_2, alias, status, member_id) VALUES (23, '광주 광산구 하남산단6번로 133', '삼성전자 그린시티 주차장 G5 자전거 보관소', '싸피', true, 16);
